# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d85a1be53e746fa6f57b96b4f5462cbd584376778ccbd1038d814ed11ee75031bef7283fc86375eefb9171ff31a2064b45a449bbfc5958f2d4bdf1756b11f11

test:
  secret_key_base: 5fd46a8f700e1c686fd541560cec0397903250001ee33003e3121b1f99e26867104b27d8ce8704c4e8adde7546d7023853581c4c29f53ee9c78e9fc18fc87c8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
